// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.12.4
// source: tosacceptance.proto

package bindings

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ToSAcceptance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	One   string `protobuf:"bytes,1,opt,name=one,proto3" json:"one,omitempty"`
	Two   string `protobuf:"bytes,2,opt,name=two,proto3" json:"two,omitempty"`
	Three string `protobuf:"bytes,3,opt,name=three,proto3" json:"three,omitempty"`
}

func (x *ToSAcceptance) Reset() {
	*x = ToSAcceptance{}
	mi := &file_tosacceptance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToSAcceptance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToSAcceptance) ProtoMessage() {}

func (x *ToSAcceptance) ProtoReflect() protoreflect.Message {
	mi := &file_tosacceptance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToSAcceptance.ProtoReflect.Descriptor instead.
func (*ToSAcceptance) Descriptor() ([]byte, []int) {
	return file_tosacceptance_proto_rawDescGZIP(), []int{0}
}

func (x *ToSAcceptance) GetOne() string {
	if x != nil {
		return x.One
	}
	return ""
}

func (x *ToSAcceptance) GetTwo() string {
	if x != nil {
		return x.Two
	}
	return ""
}

func (x *ToSAcceptance) GetThree() string {
	if x != nil {
		return x.Three
	}
	return ""
}

var File_tosacceptance_proto protoreflect.FileDescriptor

var file_tosacceptance_proto_rawDesc = []byte{
	0x0a, 0x13, 0x74, 0x6f, 0x73, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x49, 0x0a, 0x0d, 0x54, 0x6f, 0x53, 0x41, 0x63, 0x63, 0x65,
	0x70, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6f, 0x6e, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x77, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x77, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x68,
	0x72, 0x65, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x68, 0x72, 0x65, 0x65,
	0x42, 0x47, 0x5a, 0x45, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64,
	0x79, 0x6c, 0x61, 0x6e, 0x6d, 0x61, 0x7a, 0x75, 0x72, 0x65, 0x6b, 0x2f, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2d, 0x66, 0x69, 0x6e, 0x64, 0x6d, 0x79, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6e, 0x6f,
	0x76, 0x61, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2f, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_tosacceptance_proto_rawDescOnce sync.Once
	file_tosacceptance_proto_rawDescData = file_tosacceptance_proto_rawDesc
)

func file_tosacceptance_proto_rawDescGZIP() []byte {
	file_tosacceptance_proto_rawDescOnce.Do(func() {
		file_tosacceptance_proto_rawDescData = protoimpl.X.CompressGZIP(file_tosacceptance_proto_rawDescData)
	})
	return file_tosacceptance_proto_rawDescData
}

var file_tosacceptance_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tosacceptance_proto_goTypes = []any{
	(*ToSAcceptance)(nil), // 0: ToSAcceptance
}
var file_tosacceptance_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tosacceptance_proto_init() }
func file_tosacceptance_proto_init() {
	if File_tosacceptance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tosacceptance_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tosacceptance_proto_goTypes,
		DependencyIndexes: file_tosacceptance_proto_depIdxs,
		MessageInfos:      file_tosacceptance_proto_msgTypes,
	}.Build()
	File_tosacceptance_proto = out.File
	file_tosacceptance_proto_rawDesc = nil
	file_tosacceptance_proto_goTypes = nil
	file_tosacceptance_proto_depIdxs = nil
}
